const mongoose = require('mongoose');

const earningsSchema = new mongoose.Schema({
    actualEPS: Number,
    consensusEPS: Number,
    estimatedEPS: Number,
    announceTime: String,
    numberOfEstimates: Number,
    EPSSurpriseDollar: Number,
    EPSReportDate: String,
    fiscalPeriod: String,
    fiscalEndDate: String,
    yearAgo: Number,
    yearAgoChangePercent: Number,
    estimatedChangePercent: Number,
    symbolId: Number
})

const financialSchema = new mongoose.Schema({
    profitMargin: Number,
    operatingMargin: Number,
    grossMargin: Number,
    reportDate: String,
    grossProfit: Number,
    costOfRevenue: Number,
    operatingRevenue: Number,
    totalRevenue: Number,
    operatingIncome: Number,
    netIncome: Number,
    researchAndDevelopment: Number,
    operatingExpense: Number,
    currentAssets: Number,
    totalAssets: Number,
    totalLiabilities: Number,
    currentRatio: Number,
    currentCash: Number,
    currentDebt: Number,
    totalCash: Number,
    totalDebt: Number,
    shareholderEquity: Number,
    cashChange: Number,
    cashFlow: Number,
    operatingGainsLosses: Number
})
const performanceSchema = new mongoose.Schema({
    ROI: {
        '20day': Number,
        '50day': Number,
        '200day': Number,
        '1yr': Number,
    },
    _id: String,
    companyName: String,
    marketcap: Number,
    beta: Number,
    week52high: Number,
    week52low: Number,
    week52change: Number,
    shortInterest: Number,
    shortDate: String,
    dividendRate: Number,
    dividendYield: Number,
    exDividendDate: Number,
    latestEPS: Number,
    latestEPSDate: String,
    sharesOutstanding: Number,
    float: Number,
    returnOnEquity: Number,
    consensusEPS: Number,
    numberOfEstimates: Number,
    EPSSurpriseDollar: Number,
    EPSSurprisePercent: Number,
    symbol: String,
    EBITDA: Number,
    revenue: Number,
    grossProfit: Number,
    cash: Number,
    debt: Number,
    ttmEPS: Number,
    revenuePerShare: Number,
    revenuePerEmployee: Number,
    peRatioHigh: Number,
    peRatioLow: Number,
    returnOnAssets: Number,
    returnOnCapital: Number,
    profitMargin: Number,
    priceToSales: Number,
    priceToBook: Number,
    day200MovingAvg: Number,
    day50MovingAvg: Number,
    institutionPercent: Number,
    insiderPercent: Number,
    shortRatio: Number,
    year5ChangePercent: Number,
    year2ChangePercent: Number,
    year1ChangePercent: Number,
    ytdChangePercent: Number,
    month6ChangePercent: Number,
    month3ChangePercent: Number,
    month1ChangePercent: Number,
    day5ChangePercent: Number,
    day30ChangePercent: Number,
})

const generalSchema = new mongoose.Schema({
    _id: String,
    CEO: String,
    companyName: String,
    description: String,
    exchange: String,
    industry: String,
    issueType: String,
    sector: String,
    symbol: String,
    website: String
})
const analyticsSchema = new mongoose.Schema({

})

module.exports = {
    earningsSchema,
    financialSchema,
    performanceSchema,
    generalSchema,
    analyticsSchema,
}